// <auto-generated />
using System;
using Maksby.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maksby.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260109153702_addClientInvoices")]
    partial class addClientInvoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maksby.Data.Models.Debt.DebtInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SummaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SummaryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("DebtInvoices");
                });

            modelBuilder.Entity("Maksby.Data.Models.Debt.DebtInvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DebtInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemsId")
                        .HasColumnType("uuid");

                    b.Property<double>("PricePerKilo")
                        .HasColumnType("double precision");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DebtInvoiceId");

                    b.HasIndex("ItemsId");

                    b.ToTable("DebtInvoiceItem");
                });

            modelBuilder.Entity("Maksby.Data.Models.Debt.DebtTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DebtInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DebtInvoiceId");

                    b.HasIndex("SupplierId");

                    b.ToTable("DebtTransactions");
                });

            modelBuilder.Entity("Maksby.Data.Models.Debt.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Maksby.Data.Models.Debt.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Maksby.Data.Models.Employee.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Maksby.Data.Models.Employee.Salary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BasicSalary")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Deduction")
                        .HasColumnType("double precision");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<double>("NetSalary")
                        .HasColumnType("double precision");

                    b.Property<double>("OverTime")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SummaryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SummaryId");

                    b.ToTable("Salaries", (string)null);
                });

            modelBuilder.Entity("Maksby.Data.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SummaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SummaryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.ClientInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SummaryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SummaryId");

                    b.ToTable("ClientInvoices");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.ClientInvoiceProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<double>("PricePerKilo")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ClientInvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("ClientInvoiceProducts");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.ClientTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientInvoiceId");

                    b.ToTable("ClientTransactions");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PricePerKilo")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Maksby.Data.Models.Summary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ActualDebt")
                        .HasColumnType("double precision");

                    b.Property<double>("ActualIncome")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EstimatedDebt")
                        .HasColumnType("double precision");

                    b.Property<double>("EstimatedIncome")
                        .HasColumnType("double precision");

                    b.Property<double>("InitialValue")
                        .HasColumnType("double precision");

                    b.Property<double>("Revenue")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalExpenses")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalSalaries")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Summary");
                });

            modelBuilder.Entity("Maksby.Data.Models.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Maksby.Data.Models.batch.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Maksby.Data.Models.batch.BatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<double>("ItemQuantity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ItemId");

                    b.ToTable("BatchItems");
                });

            modelBuilder.Entity("Maksby.Data.Models.Debt.DebtInvoice", b =>
                {
                    b.HasOne("Maksby.Data.Models.Summary", "Summary")
                        .WithMany("DebtInvoices")
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maksby.Data.Models.Debt.Supplier", "Supplier")
                        .WithMany("DebtInvoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summary");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Maksby.Data.Models.Debt.DebtInvoiceItem", b =>
                {
                    b.HasOne("Maksby.Data.Models.Debt.DebtInvoice", "DebtInvoice")
                        .WithMany("DebtInvoiceItems")
                        .HasForeignKey("DebtInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maksby.Data.Models.Debt.Item", "Items")
                        .WithMany("DebtInvoiceItem")
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtInvoice");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Maksby.Data.Models.Debt.DebtTransaction", b =>
                {
                    b.HasOne("Maksby.Data.Models.Debt.DebtInvoice", "DebtInvoice")
                        .WithMany("DebtTransactions")
                        .HasForeignKey("DebtInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maksby.Data.Models.Debt.Supplier", "Supplier")
                        .WithMany("DebtTransactions")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtInvoice");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Maksby.Data.Models.Employee.Salary", b =>
                {
                    b.HasOne("Maksby.Data.Models.Employee.Employee", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maksby.Data.Models.Summary", "Summary")
                        .WithMany("Salaries")
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("Maksby.Data.Models.Expense", b =>
                {
                    b.HasOne("Maksby.Data.Models.Summary", "Summary")
                        .WithMany("Expenses")
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.ClientInvoice", b =>
                {
                    b.HasOne("Maksby.Data.Models.Income.Client", "Client")
                        .WithMany("ClientInvoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maksby.Data.Models.Summary", "Summary")
                        .WithMany("ClientInvoices")
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.ClientInvoiceProduct", b =>
                {
                    b.HasOne("Maksby.Data.Models.Income.ClientInvoice", "ClientInvoice")
                        .WithMany("ClientInvoiceProducts")
                        .HasForeignKey("ClientInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maksby.Data.Models.Income.Product", "Product")
                        .WithMany("ClientInvoiceProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientInvoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.ClientTransaction", b =>
                {
                    b.HasOne("Maksby.Data.Models.Income.Client", "Client")
                        .WithMany("ClientTransactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maksby.Data.Models.Income.ClientInvoice", "ClientInvoice")
                        .WithMany("ClientTransactions")
                        .HasForeignKey("ClientInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ClientInvoice");
                });

            modelBuilder.Entity("Maksby.Data.Models.batch.Batch", b =>
                {
                    b.HasOne("Maksby.Data.Models.Income.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Maksby.Data.Models.batch.BatchItem", b =>
                {
                    b.HasOne("Maksby.Data.Models.batch.Batch", "Batch")
                        .WithMany("BatchItems")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maksby.Data.Models.Debt.Item", "Item")
                        .WithMany("BatchItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Maksby.Data.Models.Debt.DebtInvoice", b =>
                {
                    b.Navigation("DebtInvoiceItems");

                    b.Navigation("DebtTransactions");
                });

            modelBuilder.Entity("Maksby.Data.Models.Debt.Item", b =>
                {
                    b.Navigation("BatchItems");

                    b.Navigation("DebtInvoiceItem");
                });

            modelBuilder.Entity("Maksby.Data.Models.Debt.Supplier", b =>
                {
                    b.Navigation("DebtInvoices");

                    b.Navigation("DebtTransactions");
                });

            modelBuilder.Entity("Maksby.Data.Models.Employee.Employee", b =>
                {
                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.Client", b =>
                {
                    b.Navigation("ClientInvoices");

                    b.Navigation("ClientTransactions");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.ClientInvoice", b =>
                {
                    b.Navigation("ClientInvoiceProducts");

                    b.Navigation("ClientTransactions");
                });

            modelBuilder.Entity("Maksby.Data.Models.Income.Product", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("ClientInvoiceProducts");
                });

            modelBuilder.Entity("Maksby.Data.Models.Summary", b =>
                {
                    b.Navigation("ClientInvoices");

                    b.Navigation("DebtInvoices");

                    b.Navigation("Expenses");

                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("Maksby.Data.Models.batch.Batch", b =>
                {
                    b.Navigation("BatchItems");
                });
#pragma warning restore 612, 618
        }
    }
}
